compute_environment: LOCAL_MACHINE

# gpu_ids: "0"  # 0,1,2,3,4,5,6,7 
# num_processes: 1

gpu_ids: all
num_processes: 8

debug: false
deepspeed_config:
  deepspeed_config_file: /path/to/your/configs/zero2.yaml
  # deepspeed_config_file: /path/to/your/configs/zero2_offload.yaml
  # deepspeed_config_file: /path/to/your/configs/zero3.yaml
  # deepspeed_config_file: /path/to/your/configs/zero3_offload.yaml
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
